netsuite.sys.api:
  host: "netsuite-sys-dev-api.us-e2.cloudhub.io"
  port: "80"
  basePath: "api"
  client_secret: "![udlDhyepWPUXp4AdeCPhnBq6wrl5XMS9d5hyyCwUk7nDA8lKR9wY1O4GpOVtpm3Y]"
  client_id: "![MTvAcXeF5xiP6rghvtWMnGW0/eeWleiPtitRi9OgE9rvwx4EzrOe0l316m4Sx3Rr]"
  
 
 
salesforce.sys.api:
  host: "salesforce-sys-dev-api.us-e2.cloudhub.io"
  port: "80"
  basePath: "api"
  client_secret: "![hU4Ya8aKrSKp53JEm3A7Ks5abidKC811814fNYZ/fxHAqJzxp4KbHXjNC0JT1tWr]"
  client_id: "![FYAw09kZxJvBAqffMOi11RCYPhqFceyUFhFvM6IXsVpSQd/vXUohlRfSX2evBu8o]"
  
  
http:
  port: "8083"
  
  
smtp:
  password: "![lU0SbuFAO55ODoiDxjkaBA==]"
  fromAddress: "![zMxrVNPS84OBVA5bRJ2DymVTwHCB7Hqe1bPgOows4wQ=]"
  toAddress: "![PwSyz0w7owJslImkJodpzOhcA6rqT0nDjyuFKIztH+4=]"
  host: "smtp.ipage.com"
  port: "587"
  user: "prathamesh.kadam@infometry.net"